name: flutter_project_template_riverpod
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #* UI
  cached_network_image: ^3.1.0
  flash: ^2.0.1
  flutter_keyboard_visibility: ^5.0.3
  google_fonts: ^2.1.0

  #* Icons
  flutter_vector_icons: ^1.0.0

  # * Firebase
  firebase_analytics: ^8.3.2
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_messaging: ^10.0.7

  # * Local notification
  awesome_notifications: ^0.0.6+10

  #* Network
  dio: ^4.0.0
  pretty_dio_logger: ^1.2.0-beta-1

  #* Dart data class
  freezed_annotation: ^0.14.3
  json_serializable: ^5.0.0

  #* State management
  hooks_riverpod: ^1.0.0-dev.7

  #* Logging
  logging: ^1.0.1

  #* Routing
  auto_route: ^2.3.2

  #* Persistent storage
  hive_flutter: ^1.1.0

  #* Localization
  easy_localization: ^3.0.0

  #* Date Time util
  jiffy: ^4.1.0

  #* Linter
  very_good_analysis: ^2.3.0

  #* Misc
  collection: ^1.15.0
  dartz: ^0.10.0
  money2: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #* Code generators
  auto_route_generator: ^2.3.2
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.3
  freezed: ^0.14.3

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    # Translation folder path containing .json files
    # run in terminal to generate localization keys:
    # flutter pub run easy_localization:generate -f keys -S assets/translations -O lib/extra/langs -o locale_keys.g.dart
    - assets/translations/