name: flutter_project_template_riverpod
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #* UI
  cached_network_image: ^3.2.0
  flash: ^2.0.3+2
  flutter_keyboard_visibility: ^5.1.0
  google_fonts: ^2.2.0

  #* Icons
  flutter_vector_icons: ^1.0.0

  #* Firebase
  firebase_analytics: ^9.0.5
  firebase_core: ^1.11.0
  firebase_crashlytics: ^2.4.5
  firebase_messaging: ^11.2.5

  #* Local notification
  awesome_notifications: ^0.6.19

  #* Network
  dio: ^4.0.4
  pretty_dio_logger: ^1.2.0-beta-1

  #* Dart data class
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

  #* State management
  hooks_riverpod: ^1.0.3

  #* Logging
  logging: ^1.0.2

  #* Routing
  auto_route: ^3.2.1

  #* Persistent storage
  flutter_secure_storage: ^5.0.2
  hive_flutter: ^1.1.0

  #* Localization
  easy_localization: ^3.0.0

  #* Date Time util
  jiffy: ^5.0.0

  #* Misc
  dartz: ^0.10.1
  money2: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #* Code generators
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.3
  freezed: ^1.1.1
  json_serializable: ^6.1.3

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    # Translation folder path containing .json files
    # run in terminal to generate localization keys:
    # flutter pub run easy_localization:generate -f keys -S assets/translations -O lib/extra/langs -o locale_keys.g.dart
    - assets/translations/